// <auto-generated />
namespace TeknoLojistik.Web.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class IlceAdDuzenleme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IlceAdDuzenleme));
        
        string IMigrationMetadata.Id
        {
            get { return "202004222141274_IlceAdDuzenleme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
